name: Hello World!

on:
  push:
    branches:
      - mastermaster

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: echo "Hello World! What's up?"
      - name: Current date
        run: date
      - name: Directory contents
        run: ls -l
